# Site settings
title: The Maker Group
baseurl: ''
# url: http://maliagehan.github.io/maker-site

# Build settings
markdown: redcarpet
highlighter: pygments

# Jekyll-Bootstrap
JB:
    version: 2.0.3
    BASE_PATH : http://maliagehan.github.io/maker-site
